<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrangeHRM Username_securityAuthenticationuserName</name>
   <tag></tag>
   <elementGuidId>f94987ed-6d8c-40f0-a18b-4254a9d93705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#securityAuthentication_userName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53c8175f-8b8e-46ae-82db-64c406bc1f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57a5cc92-5b2f-4928-81ce-4f6a99c849b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>securityAuthentication[userName]</value>
      <webElementGuid>4142a279-26e9-40da-9e4f-32e536169eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securityAuthentication_userName</value>
      <webElementGuid>5bf24ee8-a871-40b5-8fd2-44c75e0781af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;securityAuthentication_userName&quot;)</value>
      <webElementGuid>1a1785af-887b-470b-a0fc-40f18272746a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='securityAuthentication_userName']</value>
      <webElementGuid>1cc8dc46-e78b-414b-96dc-23d4f55c4082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='resetPasswordForm']/fieldset/ol/li/input</value>
      <webElementGuid>2434c636-6bf1-44f5-8804-bb21e4df7e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>6d845798-6409-4862-8f1b-ad6dde425aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'securityAuthentication[userName]' and @id = 'securityAuthentication_userName']</value>
      <webElementGuid>52a3eae3-ae15-40f0-aba9-bd2a0c559b18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
