<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password_divLoginHelpLink</name>
   <tag></tag>
   <elementGuidId>1c6b73af-e7e5-4056-9125-2de9daf41e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divLoginHelpLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#divLoginHelpLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4bc30911-b38a-42de-9f8a-1ca9595fc87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>divLoginHelpLink</value>
      <webElementGuid>00d2889f-0ada-4c9b-93f2-c5327d2eea7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divLoginHelpLink&quot;)</value>
      <webElementGuid>4eaae5df-60fc-4a5d-b612-fe5f821fe007</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='divLoginHelpLink']</value>
      <webElementGuid>42ace138-0809-4d11-b658-7ab879bf4b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div[4]</value>
      <webElementGuid>fdc8c1f3-e5c9-4e9c-b722-0ea7eba22111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]</value>
      <webElementGuid>926ffda0-2769-4629-9db2-a543a970228a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'divLoginHelpLink']</value>
      <webElementGuid>4497049b-1224-45df-ba5e-178cc8c2c9c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
