<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__systemUseremployeeNameempName</name>
   <tag></tag>
   <elementGuidId>bfbe315e-a146-49dd-90d2-05bfd8a684de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='systemUser_employeeName_empName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#systemUser_employeeName_empName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2225a54-5d2e-4d40-94b9-3c5b86642f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText ac_input</value>
      <webElementGuid>2091583f-630a-4a53-8351-dc8f111c6b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>63577771-af69-4aea-97a8-7b6f373939a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Type for hints...</value>
      <webElementGuid>0b145b07-2f6a-43e9-b7dc-bb3721c9b263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc6266b9-861d-4737-ad23-0dc196804c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>systemUser[employeeName][empName]</value>
      <webElementGuid>d4bd816e-eaca-4cce-bd19-cf342c62ecf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>systemUser_employeeName_empName</value>
      <webElementGuid>d5a81dfd-e029-4817-9da9-cbfb5b5b1eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>409961bf-82fe-4f5e-a393-ff20871d837a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;systemUser_employeeName_empName&quot;)</value>
      <webElementGuid>2128d00a-7e30-4f52-b1f5-9fcac7ed2843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='systemUser_employeeName_empName']</value>
      <webElementGuid>644b93d5-2394-4995-9f3a-78893f9d1e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSystemUser']/fieldset/ol/li[2]/input</value>
      <webElementGuid>51172f79-55bc-4d5b-b852-60f92e0af6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>2c0bec6d-c8ce-4b8a-ae2a-9631b12767b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'systemUser[employeeName][empName]' and @id = 'systemUser_employeeName_empName']</value>
      <webElementGuid>af64eb33-8c58-4e34-bddf-26ca0f3d3cfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
