<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EQALJ</name>
   <tag></tag>
   <elementGuidId>839cd4dd-bf20-4f0f-88e1-2ae0ee641127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.even > td.left > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'EQALJ')]//preceding::input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>932e1a22-4d42-4b78-b099-23f0251483ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>saveSystemUser?userId=57</value>
      <webElementGuid>c8339d39-8cc3-4a8f-a531-7aeb4c078c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EQALJ</value>
      <webElementGuid>32ace1f7-a580-4e7c-9155-9013c4dd3b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultTable&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;left&quot;]/a[1]</value>
      <webElementGuid>4cb5b605-db57-4342-a44c-9bac92fb90fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>cb26bb8c-2ef8-489b-ab56-25985f7dfbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EQALJ')]</value>
      <webElementGuid>26e9752f-2c0f-4b22-8cc8-8a028da84c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enabled'])[2]/following::a[1]</value>
      <webElementGuid>96e3c742-2c90-4fbe-9a72-7d76b1ec44bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ram sita Collings'])[1]/following::a[1]</value>
      <webElementGuid>e394e03b-6e70-4f52-9ee4-80f529cd6b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESS'])[2]/preceding::a[1]</value>
      <webElementGuid>ac0ee2a0-6a35-4ad7-9e7b-68a3694ad84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dominic Chase'])[1]/preceding::a[1]</value>
      <webElementGuid>cdac80d0-e4a3-46bc-b46e-2ee23bdf21a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EQALJ']/parent::*</value>
      <webElementGuid>01bc099f-2b1c-4c5b-ba7c-85800e294b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'saveSystemUser?userId=57')]</value>
      <webElementGuid>6a02c714-cc12-4f31-a367-5255e70b9432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>0ab9c0b5-3e01-4f28-a936-b4482f59e01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'saveSystemUser?userId=57' and (text() = 'EQALJ' or . = 'EQALJ')]</value>
      <webElementGuid>90c99586-fe51-4578-8984-68037267083e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
