<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrangeHRM - Confirmation Required_dialogDeleteBtn</name>
   <tag></tag>
   <elementGuidId>376e4723-7840-4b5e-a62b-04b54cbf4977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dialogDeleteBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dialogDeleteBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae4eb08f-9d01-48a7-ab4c-7500f905ed6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8095fbe8-104d-498f-af27-7a72a427d838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn hover</value>
      <webElementGuid>551dfa89-1837-458d-a941-2708c6cb858b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>b9fab445-2ce7-4ad4-8c99-722a8dec9255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialogDeleteBtn</value>
      <webElementGuid>7abedaae-1f37-4aef-9af7-68d8c0c6ad02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>c9793321-324f-44d2-9945-9817ad1e32b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogDeleteBtn&quot;)</value>
      <webElementGuid>b6cdd197-d809-4230-9623-8dc0e5357968</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dialogDeleteBtn']</value>
      <webElementGuid>ec478545-5053-499d-afbc-d0b5d2f8534a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteConfModal']/div[3]/input</value>
      <webElementGuid>9d55165a-d32a-4e3e-bbcd-b9408fb4f761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>a8a92107-3a38-4d9d-b737-d1f30130944f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'dialogDeleteBtn']</value>
      <webElementGuid>a72e1841-90ba-4126-9b83-6370536e6d26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
