<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jobTitlejobTitle</name>
   <tag></tag>
   <elementGuidId>6c87ad59-14c5-4a88-8c8f-d704dd44c9a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobTitle_jobTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobTitle_jobTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>459ca85e-b68b-443a-9251-4d70c6fc307b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e843cef-43df-41b4-a544-a51d2d66d7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTitle[jobTitle]</value>
      <webElementGuid>89690efa-1725-4dbd-9f62-c6f6b91dde95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7a0d2a30-63cb-45ab-a6c3-589af09afc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTitle_jobTitle</value>
      <webElementGuid>94e75dd3-cbd5-4f0e-a9cd-b5c4e9403e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitle_jobTitle&quot;)</value>
      <webElementGuid>c8212bcd-f016-4d58-8bed-ed8aa0de7bbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobTitle_jobTitle']</value>
      <webElementGuid>e0f3883e-a718-4a1a-a274-718b886f09b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSavejobTitle']/fieldset/ol/li/input</value>
      <webElementGuid>f597091e-6448-4c02-8529-acd3ddb6e13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>c8598dff-9d59-4ffd-80bb-a80d8e7b1314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobTitle[jobTitle]' and @id = 'jobTitle_jobTitle']</value>
      <webElementGuid>0266b264-ff61-467d-890b-78bbf095606d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
