<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Employment Status</name>
   <tag></tag>
   <elementGuidId>a318c5ba-46d4-4f4a-ad15-767b57a46b03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_admin_employmentStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_admin_employmentStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e599c938-f202-4d62-8981-6992480cb402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/admin/employmentStatus</value>
      <webElementGuid>e9ca0576-9724-4046-b942-0d701dcda10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_admin_employmentStatus</value>
      <webElementGuid>1389675f-9acc-4201-ba73-9fcdb58d00e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employment Status</value>
      <webElementGuid>2ca95774-d77d-40fb-bc8e-69585833ca74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_admin_employmentStatus&quot;)</value>
      <webElementGuid>d343f3a5-d4d6-4cd9-9b18-989825b1c326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_admin_employmentStatus']</value>
      <webElementGuid>200cbe7d-2100-497b-84e8-66aad59b809d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>096ce717-1d6d-4509-a358-89a1c1d2d12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Employment Status')]</value>
      <webElementGuid>32f2152a-1b8f-4485-9b15-2d0de03b7929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay Grades'])[1]/following::a[1]</value>
      <webElementGuid>29727c06-cb40-45aa-9ecd-15974fdb6fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Titles'])[1]/following::a[2]</value>
      <webElementGuid>d7ade60a-1c97-42c2-936e-6f5ef10f428c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Categories'])[1]/preceding::a[1]</value>
      <webElementGuid>bb5a46d1-b153-4812-b420-f7df53285bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Shifts'])[1]/preceding::a[2]</value>
      <webElementGuid>90fc050b-2492-44e6-bbb4-cf7554c004e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employment Status']/parent::*</value>
      <webElementGuid>e042cc7f-0cdc-46a8-b4b9-16195c9e6cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/admin/employmentStatus')]</value>
      <webElementGuid>8be17c42-b736-46c6-b6d0-8b909d85b864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>8aaaba8f-8242-4f04-b64c-f59c21f24ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/admin/employmentStatus' and @id = 'menu_admin_employmentStatus' and (text() = 'Employment Status' or . = 'Employment Status')]</value>
      <webElementGuid>4ab1fcad-01f7-4444-804d-dea3aa797a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
