<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employment Status_btnDelete</name>
   <tag></tag>
   <elementGuidId>6a36c046-141b-4dc7-925d-ad707be3eb0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDelete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnDelete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5df0750-41ad-481a-bba7-b01e985c1e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6c41047d-d6c4-4ed8-b150-30377b8e50b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete hover</value>
      <webElementGuid>7d56ab5c-8dbc-412c-8708-f5d8786816d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>1154f50f-3fdd-4b55-a915-e732a69a4c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>5a5bc5f2-a4b1-4bd9-bb03-56a79f9aaa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>23d217ac-1abf-44e6-ac97-b280ba557766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>de3d9825-a066-490d-b810-34fcf0f6e728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#deleteConfModal</value>
      <webElementGuid>29ad53a0-25e1-4f8e-8245-3b8957e9331e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDelete&quot;)</value>
      <webElementGuid>b31af592-5b21-4306-9c02-e05a4ea3bd38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnDelete']</value>
      <webElementGuid>3b2fb6c5-7cfd-4224-9d4d-edb3e2a242c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmList_ohrmListComponent']/div/input[2]</value>
      <webElementGuid>94673ab1-fcb2-4b89-83ac-2ae1a66c950d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[2]</value>
      <webElementGuid>5f3665fa-a2a0-4842-a77e-923b95b6182b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnDelete' and @name = 'btnDelete']</value>
      <webElementGuid>27e38013-db74-45cf-a523-0d87302fad4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
