<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__empStatusname</name>
   <tag></tag>
   <elementGuidId>dc097069-33a0-484d-b2ab-127abcd603ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empStatus_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empStatus_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8163744f-ecf4-48ee-bf74-b514eae5fafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4651b36a-d7b7-4a0c-9f11-8fc8a45918d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empStatus[name]</value>
      <webElementGuid>ebfcd380-401a-46f9-b935-e8a49d2e483a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>2110c052-c072-4a1f-a5de-3203d84b979d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>3d57ae21-4683-4d3d-9e3e-e96e95049829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empStatus_name</value>
      <webElementGuid>5ec1c20b-f2c2-4d1d-acd6-409419106ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empStatus_name&quot;)</value>
      <webElementGuid>4de4024e-1034-4a19-88fd-3b67aca65584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empStatus_name']</value>
      <webElementGuid>4a71cdf9-a853-44da-a278-f1c995f06206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpStatus']/fieldset/ol/li/input</value>
      <webElementGuid>9362a53b-6832-4f5f-be5e-0f00ff3cdebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>f9a920a4-9b79-4b47-90b8-3535223982f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empStatus[name]' and @id = 'empStatus_name']</value>
      <webElementGuid>7c474f0c-ab9d-4cc2-96bb-dab5b91303ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
